FROM node:20-slim
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Crucial: Astro server needs to listen on 0.0.0.0
ENV HOST=0.0.0.0
ENV PORT=8080
EXPOSE 8080

# This matches the entry point generated by the Node adapter
CMD ["node", "./dist/server/entry.mjs"]
